### PR TITLE
Add related content

### PR DESCRIPTION
**Pull request by KimberleyCook**
## What have I done

Add the related content hook
## Why

So that the case studies can have related content at the bottom of them

### CODE REVIEW

**Comment by iamdeaneyelid** [comment]
Hi Kim,

Thanks for doing this. However it looks like the images don't exactly work. I've attached a screenshot. It's looking like the background image is repeating.

screen shot 2016-10-03 at 12 10 29

**Comment by KimberleyCook** [comment]
Ok, amends will get done in the other repo. This one can still get merged though as it's CMS amends not design.

**Comment by KimberleyCook** [comment]
hmm, I have added `background-repeat: none` but even before that I was not seeing that. Are you on `related-content-amends` branch in the `shortlist-media-family` repo?

**Comment by iamdeaneyelid** [comment]
Yes

**Pull request merged**
